version: "3.8"
services:
  web:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - api
  api:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_URI: "${DB_URI}"
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mongo:6.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 27017:27017
    volumes:
      - db-data:/data

volumes:
  db-data:
